# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-json
        types: [file]  # override `types: [json]`
        files: \.(json|json.sample)$
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: pretty-format-json
        types: [file]  # override `types: [json]`
        files: \.(json|json.sample)$
        args: [--autofix, --no-sort-keys]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
    - id: commitlint
