# Generated by Django 4.1.3 on 2023-02-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_tag", models.CharField(max_length=255)),
                ("identity", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "active"), ("Inactive", "inactive")],
                        default="Active",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="gitAcces",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gitusername",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ssh_pub_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ssh_public_key",
        ),
        migrations.RemoveField(
            model_name="useraccessmapping",
            name="user",
        ),
        migrations.AddField(
            model_name="useraccessmapping",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="groupv2",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name="useridentity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_identity",
                to="Access.user",
            ),
        ),
        migrations.AddField(
            model_name="useraccessmapping",
            name="user_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_access_mapping",
                to="Access.useridentity",
            ),
        ),
        migrations.AddConstraint(
            model_name="useridentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Active")),
                fields=("user", "access_tag", "status"),
                name="one_active_identity_per_access_module_per_user",
            ),
        ),
    ]
