# Generated by Django 4.1.3 on 2022-12-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="gitAcces",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_manager",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_ops",
        ),
    ]
