# Generated by Django 4.1.3 on 2022-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0002_delete_gitacces_remove_user_is_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_ops",
            field=models.BooleanField(default=False),
        ),
    ]
