# Generated by Django 4.1.3 on 2023-02-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0003_alter_groupaccessmapping_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccessmapping",
            name="fail_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
