# Generated by Django 4.1.3 on 2023-01-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0004_alter_groupv2_name_useridentity"),
        ("Access", "0004_useraccessmapping_meta_data_alter_groupv2_name"),
    ]

    operations = []
