# Generated by Django 4.1.3 on 2023-01-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0005_merge_20230117_0948"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccessmapping",
            name="user_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_access_mapping",
                to="Access.useridentity",
            ),
        ),
        migrations.AddField(
            model_name="useridentity",
            name="status",
            field=models.CharField(
                choices=[("Active", "active"), ("Inactive", "inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="useridentity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_identity",
                to="Access.user",
            ),
        ),
        migrations.AddConstraint(
            model_name="useridentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Active")),
                fields=("user", "access_tag", "status"),
                name="one_active_identity_per_access_module_per_user",
            ),
        ),
    ]
