# Generated by Django 4.1.3 on 2023-01-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0005_merge_20230117_0948"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccessmapping",
            name="module_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_identity",
                to="Access.useridentity",
            ),
        ),
        migrations.AlterField(
            model_name="useridentity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="module_identity",
                to="Access.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useridentity",
            unique_together={("access_tag", "user")},
        ),
    ]
