# Generated by Django 4.1.3 on 2023-01-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("Access", "0007_alter_useraccessmapping_user"),
        ("Access", "0008_alter_useraccessmapping_module_identity"),
        ("Access", "0009_useridentity_status_and_more"),
        ("Access", "0010_remove_useraccessmapping_module_identity_and_more"),
        ("Access", "0011_alter_useraccessmapping_user_identity"),
        ("Access", "0012_alter_useridentity_unique_together_and_more"),
    ]

    dependencies = [
        ("Access", "0006_useraccessmapping_module_identity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccessmapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_membership",
                to="Access.user",
            ),
        ),
        migrations.AddField(
            model_name="useridentity",
            name="status",
            field=models.CharField(
                choices=[("Active", "active"), ("Inactive", "inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.RemoveField(
            model_name="useraccessmapping",
            name="module_identity",
        ),
        migrations.AddField(
            model_name="useraccessmapping",
            name="user_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_access",
                to="Access.useridentity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useridentity",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="useridentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Active")),
                fields=("user", "access_tag", "status"),
                name="one_active_identity_per_access_module_per_user",
            ),
        ),
    ]
