# Generated by Django 4.1.3 on 2023-01-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0006_useraccessmapping_module_identity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccessmapping",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_membership",
                to="Access.user",
            ),
        ),
    ]
