# Generated by Django 4.1.3 on 2023-01-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0007_alter_useraccessmapping_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccessmapping",
            name="module_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership",
                to="Access.useridentity",
            ),
        ),
    ]
