# Generated by Django 4.1.3 on 2023-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0008_alter_useraccessmapping_module_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="useridentity",
            name="status",
            field=models.CharField(
                choices=[("Active", "active"), ("Inactive", "inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="useraccessmapping",
            name="module_identity",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
