# Generated by Django 4.1.3 on 2023-01-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0009_useridentity_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccessmapping",
            name="module_identity",
        ),
        migrations.AddField(
            model_name="useraccessmapping",
            name="user_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_identity",
                to="Access.useridentity",
            ),
        ),
    ]
