# Generated by Django 4.1.3 on 2023-01-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0011_alter_useraccessmapping_user_identity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useridentity",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="useridentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Active")),
                fields=("user", "access_tag", "status"),
                name="one_active_identity_per_access_module_per_user",
            ),
        ),
    ]
