# Generated by Django 4.1.3 on 2023-01-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Access",
            "0007_alter_useraccessmapping_user_squashed_0012_alter_useridentity_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccessmapping",
            name="user",
        ),
        migrations.AlterField(
            model_name="useraccessmapping",
            name="user_identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_access_mapping",
                to="Access.useridentity",
            ),
        ),
    ]
