# Generated by Django 4.1.3 on 2023-02-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Access", "0006_useraccessmapping_user_identity_useridentity_status_and_more"),
        ("Access", "0013_remove_useraccessmapping_user_and_more"),
    ]

    operations = []
