# github action to run commit-msg hook on pull request commits and push commits to master branch
name: commit-msg
on: [push, pull_request]
jobs:
  commit-msg-hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run commit-msg hook
        run: |
            pip install pre-commit==v1.1.2
            pre-commit install
            pre-commit run --all-files
