# github action to run commit-msg hook on pull request commits and push commits to master branch
name: commit-msg
on: [push]
jobs:
  commit-msg-hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run commit-msg hook
        run: |
            pip install pre-commit==2.21.0
            pre-commit install --install-hooks --overwrite
            pre-commit autoupdate
            pre-commit run --all-files --show-diff-on-failure --color always
